---
# Source: loki-distributed/templates/runtime-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-loki-distributed-runtime
  namespace: default
  labels:
    helm.sh/chart: loki-distributed-0.76.1
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.9.2"
    app.kubernetes.io/managed-by: Helm
data:
  runtime.yaml: |
    
    {}
