---
# Source: loki-distributed/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-loki-distributed
  namespace: default
  labels:
    helm.sh/chart: loki-distributed-0.76.1
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.9.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
