---
# Source: loki-distributed/templates/ruler/configmap-ruler.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-loki-distributed-ruler-rules-tenant-foo
  labels:
    helm.sh/chart: loki-distributed-0.76.1
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.9.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ruler
data:
  gateway.txt: |
    groups:
    - name: nginx_access_error
     rules:
       - alert: NginxAccessLogError
         expr: sum by (method, request_proto, vhost, path) ( count_over_time({scrape_job="gateway-nginx", filename="/mnt/access.log"}[1m]|json| status=~"5.*")) > 0
         for: 1m
         labels:
           severity: critical
         annotations:
           summary: nginx access error
    - name: nginx_access_slow
     rules:
       - alert: NginxAccessLogSlow
         expr: sum by (method, request_proto, vhost, path) ( count_over_time({scrape_job="gateway-nginx", filename="/mnt/access.log"}[1m]|json| request_time > 1)) >0
         for: 1m
         labels:
           severity: critical
         annotations:
           summary: nginx access slow
  middleware.txt: |
    groups:
    - name: middleware_seata_error
      rules:
        - alert: TestMiddlewareLogError
          expr: count_over_time({app="seata-server",namespace="dev",scrape_job="kubernetes-pods"}[1m]|= "Exception") > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: test middleware log error
  service.txt: |
    groups:
    - name: service_error
      rules:
        - alert: TestServiceLogError
          expr: count_over_time({scrape_job="service",namespace="dev",app=~"ct-k8s-ctbigdata-.*"}[1m]|= "Exception"!="ServiceException") > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: test service log error
