---
# Source: loki-distributed/templates/querier/servicemonitor-querier.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-loki-distributed-querier
  labels:
    helm.sh/chart: loki-distributed-0.76.1
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.9.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: querier
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-distributed
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: querier
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http
      scheme: http
