{
 "title": "生产环境-polardb-慢SQL-总体+详情",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "数据库名称",
    "query": "select distinct db_name from polardb_slow_log order by db_name "
   },
   {
    "name": "sql_template_id",
    "label": "SQL模板ID",
    "query": "select distinct sql_template_id from polardb_slow_log WHERE db_name in ($db_name) order by  sql_template_id"
   }
  ]
 },
 "panels": [
  {
   "title": "慢SQL-模板",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    t.data_timestamp AS \"time\",\r\n    count( 1 ) AS \"每小时出现次数\"\r\nFROM\r\n    (\r\n        SELECT DISTINCT sql_template_id,\r\n                        data_timestamp\r\n        FROM\r\n            polardb_slow_log\r\n        WHERE\r\n            $__unixEpochFilter(data_timestamp)\r\n          AND db_name IN ( $db_name )\r\n          and sql_template_id in ($sql_template_id)\r\n    ) t\r\nGROUP BY\r\n    t.data_timestamp\r\nORDER BY\r\n    t.data_timestamp"
    }
   ]
  },
  {
   "title": "慢SQL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\r\n    t.data_timestamp AS \"time\",\r\n    count(1) as \"每小时出现次数\"\r\nfrom (\r\n         select data_timestamp\r\n         from polardb_slow_log\r\n         WHERE\r\n             $__unixEpochFilter(data_timestamp)\r\n           and db_name in ($db_name)\r\n           and sql_template_id in ($sql_template_id)\r\n     )t\r\ngroup by data_timestamp\r\nORDER BY data_timestamp"
    }
   ]
  },
  {
   "title": "慢SQL模板详情",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    t.id AS 'SQL模板ID',\r\n        t.db_name AS '数据库',\r\n        t.times AS '次数',\r\n        FLOOR( t.avg_qt ) AS '平均耗时(秒)',\r\n        t.max_qt AS '最大耗时(秒)',\r\n        t.min_qt AS '最小耗时(秒)',\r\n        t.parse_row_counts AS '扫描行数',\r\n        t.sql_text AS 'SQL模板'\r\nFROM\r\n    (\r\n        SELECT\r\n            pslt.id,\r\n            pslt.db_name,\r\n            CONVERT ( pslt.sql_text USING utf8 ) sql_text,\r\n            psl.data_timestamp,\r\n            psl.parse_row_counts,\r\n            psl.execution_start_time,\r\n            count( 1 ) AS times,\r\n            avg( psl.query_times ) avg_qt,\r\n            max( psl.query_times ) max_qt,\r\n            min( psl.query_times ) min_qt\r\n        FROM\r\n            polardb_slow_log_template pslt\r\n                LEFT JOIN polardb_slow_log psl ON pslt.db_name = psl.db_name\r\n                AND pslt.id = psl.sql_template_id\r\n        WHERE $__unixEpochFilter(data_timestamp) and pslt.db_name in ($db_name) and pslt.id in ($sql_template_id)\r\n        GROUP BY\r\n            db_name,\r\n            sql_text\r\n    ) t\r\nORDER BY\r\n    t.times DESC"
    }
   ]
  },
  {
   "title": "慢SQL详细清单",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    execution_start_time as \"执行开始时间\",\r\n    query_times as \"耗时(秒)\",\r\n    db_name as \"数据库\",\r\n    parse_row_counts as '扫描行数',\r\n        convert(sql_text using utf8) \"sql\"\r\nFROM polardb_slow_log\r\nWHERE\r\n    $__unixEpochFilter(data_timestamp)\r\n  and db_name in ($db_name)\r\n  and sql_template_id in ($sql_template_id)\r\nORDER BY data_timestamp"
    }
   ]
  }
 ]
}