---
# Source: loki-distributed/templates/query-frontend/servicemonitor-query-frontend.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-loki-distributed-query-frontend
  labels:
    helm.sh/chart: loki-distributed-0.76.1
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.9.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-distributed
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: query-frontend
  endpoints:
    - port: http
      scheme: http
