apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitor-event
data:
  config.yaml: |
    logLevel: warn
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "loki"
    receivers:
      - name: "loki"
        loki:
          streamLabels:
            scrape_job: kubernetes-cluster-event
          url: http://loki-loki-distributed-gateway.logging/loki/api/v1/push