{
 "title": "k8s-pod-schedule",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "NameSpace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU/Memory已调度率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})/sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})/sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU调度量",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "cpu-已调度量"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})-sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "cpu-可调度量"
    }
   ]
  },
  {
   "title": "memory调度量",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "momory-已调度量"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})-sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "momory-可调度量"
    }
   ]
  },
  {
   "title": "调度量-限制量-运行量(平均)--运行量(最大): CPU/Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count(kube_pod_container_resource_requests{namespace=~\"$NameSpace\", resource=\"cpu\"}) by (container)"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"$NameSpace\", resource=\"cpu\"}) by (container)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"$NameSpace\", resource=\"cpu\"}) by (container)"
    },
    {
     "expr": "avg(container_cpu_usage_seconds_total{namespace=~\"$NameSpace\"}/100000) by (container)"
    },
    {
     "expr": "max(container_cpu_usage_seconds_total{namespace=~\"$NameSpace\"}/100000) by (container)"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=~\"$NameSpace\",resource=\"memory\"}) by (container)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=~\"$NameSpace\",resource=\"memory\"}) by (container)"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"$NameSpace\"}) by (container)"
    }
   ]
  }
 ]
}