{
 "title": "k8s-pod",
 "tags": [
  "StarsL.cn",
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "NameSpace",
    "label": "命名空间",
    "query": {
     "query": "label_values(kube_namespace_labels{},namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"},pod)"
    }
   },
   {
    "name": "Container",
    "label": "微服务(容器名)",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\",pod=~\"$Pod\"},container)"
    }
   },
   {
    "name": "Node",
    "label": "主机",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{namespace=~\"$NameSpace\", container=~\"$Container\", pod=~\"$Pod\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "node-level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "容器所在主机-CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$Node\",mode=\"idle\"}[1m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "容器所在主机-Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{instance=~\"$Node\"}/node_memory_MemTotal_bytes{instance=~\"$Node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "容器所在主机-磁盘性能",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$Node\"}[1m])",
     "legendFormat": "{{instance}}-{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$Node\"}[1m])",
     "legendFormat": "{{instance}}-{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "容器所在主机-网络性能",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\", instance=~'$Node'}[2m])*8/120",
     "legendFormat": "{{instance}}-{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$Node'}[2m])*8/120",
     "legendFormat": "{{instance}}-{{device}}_transmit"
    }
   ]
  },
  {
   "title": "rc-level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "服务总CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}[2m])) by (container) ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "服务总内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "pod-level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}[2m])) by (container, pod, node) \r\n/\r\n (sum(container_spec_cpu_quota{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}/100000) by (container, pod, node)) * 100",
     "legendFormat": "{{container}}:  {{ pod }}: {{node}}"
    }
   ]
  },
  {
   "title": "内存率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}) by (container, pod) * 100",
     "legendFormat": "{{ pod }}：{{container}}"
    }
   ]
  },
  {
   "title": "CPU量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}[2m])) by (container, pod) ",
     "legendFormat": "{{container}}:  {{ pod }}"
    }
   ]
  },
  {
   "title": "内存量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}) by (container, pod)",
     "legendFormat": "{{container}}:  {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}) by (container,pod)",
     "legendFormat": "limits：{{ pod }}：{{container}}"
    },
    {
     "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}",
     "legendFormat": "Heap：{{ pod }}：{{container}}"
    }
   ]
  },
  {
   "title": "网络量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (sum (rate (container_network_receive_bytes_total{pod=~\"$Pod\",image!=\"\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod)  group_right kube_pod_container_info{container!=\"exporter\"}) by(container) *8",
     "legendFormat": "{{container}}:  {{ pod }} 流入"
    },
    {
     "expr": "sum (sum (rate (container_network_transmit_bytes_total{pod=~\"$Pod\",image!=\"\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod)  group_right kube_pod_container_info{container!=\"exporter\"}) by(container) *8",
     "legendFormat": "{{container}}:  {{ pod }} 流出"
    }
   ]
  },
  {
   "title": "磁盘量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=~\"$NameSpace\", node=~\"^$Node$\", persistentvolumeclaim=~\".*$Container.*\"}-kubelet_volume_stats_available_bytes{namespace=~\"$NameSpace\", node=~\"^$Node$\", persistentvolumeclaim=~\".*$Container.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "低于建议CPU值的容器",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[10m])) by (container, pod) /0.8\r\n-\r\nsum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[1m])) by (container, pod) ",
     "legendFormat": "{{container}}: {{pod}}"
    }
   ]
  },
  {
   "title": "低于建议内存值的容器",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) /0.8\r\n-\r\nsum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) >0",
     "legendFormat": "{{container}}: {{pod}}"
    }
   ]
  }
 ]
}