apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    jmx-type: service-jvm
  name: service-java
  namespace: test
spec:
  endpoints:
    - interval: 15s
      port: metrics
      path: /metrics
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_endpoints_label_jmx_type
          targetLabel: job
  selector:
    matchLabels:
      jmx-type: service-jvm
#  namespaceSelector:
#    matchNames:
#      - test
